[package]
name = "mdbook-renderer"
version = "0.1.0"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"

[dependencies]
mdbook-core = { path = "../mdbook-core" }
error-chain = "0.12"
serde = "1"
serde_derive = "1"
log = "0.4"
serde_json = "1"
shlex = "0.1"
